FROM maven:3.9.6-eclipse-temurin-17

WORKDIR /app

COPY . /app

RUN mvn clean javadoc:javadoc
ы
CMD ["sh", "-c", "echo 'Документация находится в /app/target/site/apidocs' && ls /app/target/site/apidocs"]
