name: Java CI (Без Maven)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v3

    - name: Установка JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'

    - name: Компиляция и запуск
      run: |
        javac src/main/java/org/example/*.java
        java -cp src/main/java org.example.Main
